#!/usr/bin/env Rscript
# Script created by Zoe Clarke, May 2020
# Last updated May 15, 2020
# run chmod +x clustering.R to make executable

options(warn = -1)

require(docopt)
'Usage:
  clustering.R [-i <input> -o <output>]
  clustering.R (-h | --help)

Options:
  -h --help Show this screen.
  -i Input directory [default: filtered_gene_bc_matrix].
  -o Output file/sample base name.
' -> doc

opts <- docopt(doc)

# Creating the Seurat object only requires Seurat to be loaded
library(Seurat)

dir <- getwd() # Make everything relative to working directory

# Load in data
sobj.data <- Read10X(data.dir = file.path(dir, opts["-i"]))

# Change gene names
# Read in gene conversion table
geneTable <- read.csv("~/Documents/AliotoAlignment/ncbi_data/finalAliotoWoodchuckGeneNames.csv")
# Isolate current gene names
genes <- sobj.data@Dimnames[[1]]
# Remove beginning MONAX5
genes <- as.character(lapply(genes, function(x) gsub("MONAX5_", "", x)))
# Loop through smaller list to replace all possible genes with human
# gene names 
for (j in 1:nrow(geneTable)) {
  woodchuckGene <- as.character(geneTable$woodchuckGenes[j])
  humanGene <- as.character(geneTable$humanGenes[j])
  geneNumber <- grep(woodchuckGene, genes)
  genes[geneNumber] <- humanGene
}
# Also replace weird WHV names
genes <- as.character(lapply(genes, function(x) gsub("WHV____", "", x)))
# Return these labels to object
sobj.data@Dimnames[[1]] <- genes

# Create Seurat object
sobj <- CreateSeuratObject(counts = sobj.data,
                           assay = "RNA",
                           min.cells = 3,
                           min.features = 200)

# Normalize data
sobj <- NormalizeData(sobj,
                      normalization.method = "LogNormalize",
                      scale.factor = 10000)

# Identify highly variable features
sobj <- FindVariableFeatures(sobj,
                             selection.method = "vst",
                             nfeatures = 2000)
# Gne names stored here:
# sobj@assays$RNA@var.features

# Scale data
all.genes <- rownames(sobj)
sobj <- ScaleData(sobj,
                  features = all.genes)

# Perform linear dimensional reduction on the most highly variable features
sobj <- RunPCA(sobj,
               features = VariableFeatures(object = sobj))

# Construct shared nearest neighbour graph
sobj <- FindNeighbors(sobj)

# Get UMAP and tSNE
sobj <- RunTSNE(sobj)
sobj <- RunUMAP(sobj, dims = 1:50)

# Save Seurat object
saveRDS(sobj, file = file.path(dir, paste(opts["o"], "_sobj.RDS", sep = "")))

# Perform clustering with scClustViz
# Note that the following section of code requires these packages:
library(scClustViz)
library(viridis)
library(presto)
library(cluster)
library(viridisLite)
library(shiny)

scSeurat <- sobj
DE_bw_clust <- TRUE
FDRthresh <- 0.01
seurat_resolution <- 0
sCVdata_list <- list()

while(DE_bw_clust) {
  seurat_resolution <- seurat_resolution + 0.2
  # ^ iteratively incrementing resolution parameter
  
  scSeurat <- FindClusters(scSeurat,
                           resolution=seurat_resolution,
                           print.output=F)
  message(" ")
  message("------------------------------------------------------")
  message(paste0("--------  res.",seurat_resolution," with ",
                 length(levels(Idents(scSeurat)))," clusters --------"))
  message("------------------------------------------------------")
  curr_sCVdata <- CalcSCV(inD=scSeurat,
                          cl=Idents(scSeurat),
                          # ^ your most recent clustering results get stored in the Seurat "ident" slot
                          assayType = "RNA",
                          exponent=2,
                          # ^ since you used scran for normalization, data is in log2 space.
                          pseudocount=1,
                          DRthresh=0.1,
                          DRforClust="pca",
                          calcSil=T,
                          calcDEvsRest=T,
                          calcDEcombn=T)
  
  DE_bw_NN <- sapply(DEneighb(curr_sCVdata,FDRthresh),nrow)
  # ^ counts # of DE genes between neighbouring clusters at your selected FDR threshold
  
  if (min(DE_bw_NN) < 1 | seurat_resolution > 2) { DE_bw_clust <- FALSE }
  # ^ If no DE genes between nearest neighbours, don't loop again.
  
  sCVdata_list[[paste0("res.",seurat_resolution)]] <- curr_sCVdata
}

# Save object generated by scClustViz
save(sCVdata_list,
     scSeurat,
     file = file.path(dir, paste(opts["-o"], "_scClustViz.RData", sep = "")))

# At this point the following command must be run to view the scClustViz file: 
#runShiny(file.path(dir, paste(opts["-o"], "_scClustViz.RData", sep = "")))